# Generated by Django 5.0.1 on 2024-01-30 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_carttable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carttable',
            name='pid',
            field=models.ForeignKey(db_column='pid', on_delete=django.db.models.deletion.CASCADE, to='product.producttable'),
        ),
    ]
