# Generated by Django 4.2.6 on 2024-02-09 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_carttable_pid'),
    ]

    operations = [
        migrations.AddField(
            model_name='carttable',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
